package ClientServer;

public enum MessageType {

    ADDCUSTOMER,SEARCHCUSTOMER,CREATEOFFER,SEARCHOFFER,SWITCHCARDS,VERIFYPASSWORD,LOGDIN,SEARCHUSER,SEARCHDESCRIPTION,REMOVEWISH,FILTERPOKEMONDESCR
}
