package ClientServer;

public enum MessageType {

    VERIFYPASSWORD,LOGDIN,SEARCHUSER,SEARCHUSERBYID,ADDCUSTOMER,SEARCHCUSTOMER,ADDCARDPOKEMON,ADDCARDYUGI,
    POSSIBLETRADE,CREATEOFFER,RAISEOFFER, SEARCHOFFER,SEARCHTRADE,SWITCHCARDS,ENDTRADE,REMOVETRADE,
    SEARCHDESCRIPTION,REMOVEWISH,FILTERPOKEMONDESCR
}
